builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
archive:
  format: binary
release:
  github:
    owner: jetstack
    name: vault-helper

gpg_signing:
  key_id: 9A1C42C8F5AA3CE6
