# vendor in code gen tools
required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.9.5"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
