
# vendor in code gen tools
required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"
